config/routes.rb
Rails.application.routes.draw do
  resources :tarefas, only: [:index, :create, :update, :destroy]

  root "tarefas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  validates :nome, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: %i[ update destroy ]

  # GET /tarefas or /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1 or /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas or /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)
    @tarefa.save

    redirect_to tarefas_url
  end

  # PATCH/PUT /tarefas/1 or /tarefas/1.json
  def update
    @tarefa.resolvida = !@tarefa.resolvida
    @tarefa.save

    redirect_to tarefas_url
  end

  # DELETE /tarefas/1 or /tarefas/1.json
  def destroy
    @tarefa.destroy
    
    redirect_to tarefas_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarefa_params
      params.require(:tarefa).permit(:nome, :resolvida)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xploit | Webploit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      
      <%= yield %>
    </main>
  </body>
</html>

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, id: 'input') do |form| %>
    <%= form.text_field :nome, class: 'form-control', required: true %>
    <%= form.button :submit, class: 'submit-btn' %>

<% end %>

app/views/tarefas/_tarefa.html.erb
<div class="cards <%= 'resolved' if tarefa.resolvida %> ">

  <%= button_to '', tarefa, method: :patch, class: "fas fa-check btn resolved-btn #{'active' if tarefa.resolvida}" %>

  <div class="cards-info">

    <h3 class="task"> <%= tarefa.nome %> </h3>
    <p class="time"> <%= l tarefa.created_at, format: :custom %> </p>

  </div>

  <%= button_to '', tarefa, method: :delete, class: 'fas fa-times btn delete-btn'%>
</div>

app/views/tarefas/edit.html.erb
<h1>Editing tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Show this tarefa", @tarefa %> |
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/index.html.erb
<div id="tarefas">
  <header>

    <h2 id="date" <%= l Date.today %></h2>

    <p id="task-count">
      <%= @tarefas.count %> Tarefas
    </p>

    <%= render 'form', tarefa: Tarefa.new %>

  </header>

  <div id="list" class="name">

    <% @tarefas.each do |tarefa| %>
      <%= render tarefa %>
    <% end %>

  </div>

</div>

app/views/tarefas/new.html.erb
<h1>New tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tarefa %>

<div>
  <%= link_to "Edit this tarefa", edit_tarefa_path(@tarefa) %> |
  <%= link_to "Back to tarefas", tarefas_path %>

  <%= button_to "Destroy this tarefa", @tarefa, method: :delete %>
</div>